### ISSUE TITLE
Foxit PDF Reader will not upgrade

### ISSUE THREAD

**Issue by NeoFax75** [brogers5/chocolatey-package-foxitreader#2] opened 2021-10-30 18:54 UTC
I have version 10.1.4.37651 installed and tried to upgrade, but choclatey did not create any log (using chocolatey gui) and it fails everytime with not being able to remove the previous version.

**Comment by brogers5** [comment] 2021-10-31 01:30
Unfortunately, I could not reproduce an upgrade failure on either of my Windows machines or in the Chocolatey test environment. All environments used the latest available version of Chocolatey (0.11.3).

As a disclaimer, I've had little experience with using Chocolatey GUI, so feel free to correct me on any later claims/assumptions relating to it.

In all environments, I started by installing package version 10.1.4.37651 via the CLI, as I could not find an option in the GUI to install a user-defined version. From what I've observed, the only supported option for an initial-install scenario would be the latest listed version for a given package.

In the Chocolatey test environment, I wasn't able to get Chocolatey GUI v0.19.0 to successfully launch:
![image](https://user-images.githubusercontent.com/6869577/139563030-ffa7dc76-e383-4687-94db-9c15002c16ea.png)

I wasn't able to find any information on this error, so I assume this is a bug with Chocolatey GUI that I'll need to report upstream. So for now, I can only attempt reproduction from the Chocolatey test environment with the CLI.

From there, an upgrade to the latest listed version (11.1.0.52543) succeeded without issues.

I then tried the same upgrade via the CLI for my Windows machines. This likewise succeeded on both machines.

Finally, I uninstalled version 11.1.0.52543, started again with installing 10.1.4.37651, and tried an upgrade via Chocolatey GUI v0.19.0. This also succeeded on both machines. The only thing that stuck out to me is that the Package Details page did not refresh to reflect the change in version - I had to backtrack to the main dashboard for the GUI's information to properly update.

Are you certain that no log was written? In my case, Chocolatey GUI wrote Chocolatey's output log to a file in `C:\ProgramData\Chocolatey GUI\Logs`. I'm assuming the same is being done in your environment, as I could not find an option to disable logging or redirect logs elsewhere.

Regardless, I'll need a copy of a log file containing an upgrade failure to move forward with debugging this.

**Comment by NeoFax75** [comment] 2021-10-31 10:24
Here is all that shows up in my chocolatey logs:

2021-10-30 14:33:20,135 20308 [DEBUG] - XmlConfiguration is now operational

Also, one problem is Windows Control Panel did not have Foxit PDF Reader recognized as installed, so I had to install the latest version and now Chocolatey GUI shows the old version even though the newest Foxit is installed on my PC.
[chocolatey.log](https://github.com/brogers5/chocolatey-package-foxitreader/files/7448558/chocolatey.log)

**Comment by brogers5** [comment] 2021-10-31 17:41
Based on the provided log file, it looks as though it's a failure in the installer binary itself that's causing the failure:

```
2021-10-31 06:37:45,301 15040 [ERROR] - ERROR: Running ["C:\Users\Terry Milnes\AppData\Local\Temp\chocolatey\FoxitReader\11.1.0.52543\FoxitPDFReader111_L10N_Setup_Prom.exe" /verysilent ] was not successful. Exit code was '1'. See log for possible error messages.
````

Unfortunately, no other details are being printed by it to the console.

I would recommend you run the upgrade again from the CLI with the `not-silent` option:
```shell
choco upgrade foxitreader --not-silent
``` 

This will instruct Chocolatey to not use the typical command-line arguments used for a silent-install, and would show the installer wizard GUI as though you had started it directly. You'd have to manually step through the installer GUI to reproduce the problem again. Chances are it would give us a more descriptive error message that we could work with.

Alternatively, since you've already installed the latest version outside of Chocolatey, you could run the upgrade again with the Skip PowerShell option (`-n`) to skip running `chocolateyInstall.ps1` altogether (which includes running the installer binary). That ought to get you unblocked and get your version registration synced up:
```shell
choco upgrade foxitreader -n
```

**Comment by brogers5** [comment] 2021-11-07 23:18
@NeoFax75, have you had a chance to dig further into this? Do you still require assistance?

**Comment by NeoFax75** [comment] 2021-11-09 23:13
I used the advice to bring it up to what I have installed on my system and
am just waiting for a upgrade to see if it works.

**Comment by brogers5** [comment] 2022-02-01 03:40
@NeoFax75, just wanted to circle back and let you know I just pushed a new package version for v11.2.1.53537 that was released a few days ago. Be sure to keep an eye out for when it gets approved.

**Comment by brogers5** [comment] 2022-02-20 19:47
@NeoFax75, the updated package has been approved for publishing as of a week ago. Have you had a chance to try an upgrade yet?

**Comment by brogers5** [comment] 2022-03-12 13:36
Given the lack of updates, I'm closing this issue, since this issue appears to be environment-specific and is not actionable with the info currently available to me.

**Closed as completed by brogers5** 2022-03-12 13:36 UTC
Labels: more details needed
